devices:
 -  name: "SW"
    device_type: "cisco_ios"
    host: "11.0.1.200"
    username: "admin"
    password: "eve"
 -  name: "R2"
    device_type: "cisco_ios"
    host: "11.0.1.201"
    username: "admin"
    password: "eve"
 -  name: "R3"
    device_type: "cisco_ios"
    host: "11.0.1.202"
    username: "admin"
    password: "eve"